### ISSUE TITLE
short hint with short text input renders on one line

### ISSUE THREAD

**Issue by automaticdreams** [alphagov/govuk-frontend#2554] opened 2022-02-23 14:47 UTC
- Operating system:
- Browser: Safari, Chrome, Firefox
- Browser version: latest
- GOV.UK Frontend Version: 4.01

A gouvukInput with a short hint and a narrow text input renders on one line as pictured
<img width="657" alt="Screenshot 2022-02-23 at 14 37 48" src="https://user-images.githubusercontent.com/4093688/155341689-aab7562f-0888-4dba-902f-96dca2c85cfe.png">

```
  {% call govukFieldset({
    legend: {
      text: "Boarding provision",
      classes: "govuk-fieldset__legend--m",
      isPageHeading: false
    }
     }) %}

      {{ govukInput({
      label: {
        text: "Location of boarding house"
      },
      id: "boardingAddresses",
      name: "boardingAddresses",
      spellcheck: false
    }) }}
    {{ govukInput({
      label: {
        text: "Number of people living on premises?"
      },
      id: "onPremises",
      name: "onPremises",
      classes: "govuk-input--width-4",
      spellcheck: false,
      inputmode: "numeric",
      pattern: "[0-9]*",
      hint: {
        text: 'This includes pupils, teachers and other adults across all sites.'
      }
    }) }}

{% end call %}
```
this could be fixed by setting the hint text to display: block

**Comment by 36degrees** [comment] 2022-05-13 15:39
Hi @automaticdreams,

I'm going to close this issue as it's been nearly 2 months since the last activity and we haven't been able to reproduce the issue that you reported.

Of course, if you're still having this problem and are able to reply with more info then we'll be happy to re-open it and investigate further.

Thanks.

**Closed by 36degrees** 2022-05-13 15:39 UTC
Labels: 🐛 bug, submitted by user, 🕔 hours
