### ISSUE TITLE
Link hover states are not clear

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#1417] opened 2019-05-31 15:42 UTC
This issue is from a May 2019 external accessibility audit report.

**WCAG Reference**: Usability feedback only, there is no WCAG related guidelines.
**Issue ID**: DAC_Issue33
**URL**: Throughout

### Before hover
![](https://user-images.githubusercontent.com/2445413/58717364-f93e1400-83c2-11e9-8a4d-54d25643938e.png)

### On hover
![](https://user-images.githubusercontent.com/2445413/58717369-fb07d780-83c2-11e9-9b5d-729d0d040515.png)

The colour change when a user hovers over a link is not clear and this was especially difficult for low vision users to determine.

Ensuring that the state change is distinctive would benefit low vision users in particular, while benefiting all mouse users in general.

## Current Code Ref(s)
```$govuk-link-colour #005ea5 $govuk-link-hover-colour #2b8cc4```

## Low vision user comments
> “I had difficulty navigating the links on all pages because little visual feedback was presented when using mouse hover. While they did change to purple, this change was difficult to notice due to the links then looking similar to the regular text on mouse hover.”

## Solution
Offer a clearer colour change i.e. similar to that of the keyboard focus, or add/remove an underline when users hover over the links/buttons.

**Comment by nickcolley** [comment] 2019-06-11 13:05
I think it'd good to think about https://github.com/alphagov/govuk-frontend/issues/1205 as well if we did this.

**Comment by nickcolley** [comment] 2019-12-04 11:20
Hover states in general could do with a review for example the error summary links and tabs component do not have hover states (perhaps more components too).

**Comment by nickcolley** [comment] 2020-01-31 13:43
Noticed the NHS seem to have responded to this challenge too (perhaps by DAC as well!).

## Main NHS.UK website
### No interaction
![](https://user-images.githubusercontent.com/2445413/73543384-c014e280-442e-11ea-9eb1-a4e6889e1e1d.png)

### Hover with a mouse
![](https://user-images.githubusercontent.com/2445413/73543392-c73bf080-442e-11ea-9535-72044eba9f8d.png)

### Focus with a keyboard
![](https://user-images.githubusercontent.com/2445413/73543400-cdca6800-442e-11ea-93ac-0c33529c4061.png)

I think this approach could potentially be problematic because the hover and the focus style are so similar a user could be confused what they're focused on and accidentally interact with wrong element.

![](https://user-images.githubusercontent.com/2445413/73543463-eb97cd00-442e-11ea-974f-9f1316f687d4.png)

## Beta NHS.UK Service Manual

## Link with no interaction
![](https://user-images.githubusercontent.com/2445413/73543508-0a965f00-442f-11ea-826c-d35fb05db656.png)

## Link when hovered
![](https://user-images.githubusercontent.com/2445413/73543555-1b46d500-442f-11ea-82a1-3d8402a5ab12.png)

## Link when focused
![](https://user-images.githubusercontent.com/2445413/73543731-82fd2000-442f-11ea-9a29-2589a5cbb895.png)

This approach seems to be: 'if there is an underline, remove it. If there is no underline, show one'.

**Comment by nickcolley** [comment] 2020-02-06 11:36
Dave Hunter has shared some of the working notes for this iteration: 

> # First iteration
> ## Hypothesis
> - Current hover and focus styles are too similar.
> - Focus style needs to be more prominent.
> 
> **If** we make the hover style less prominent (by removing the yellow background)
> **Then** users will still be able to detect the link
> **Because** they already know where they are on the page.
> 
> ## Design examples
> ![](https://lh6.googleusercontent.com/2NYTE2-8i4YR2CpRB0kVKS_xwlHXl7XK4GVuqiGSHR3cbD1_7g8TxxTgJu-sWWqPnngYiUCOg89zOraDdm2N0DhEPC8XzThdrGAuy8PiTnikXfKsp1YGN2WhgsFWYIJduTXYLRUs)
> _Link styles before_
> 
> ![](https://lh3.googleusercontent.com/30lgzorWAd8q68K5gTU_RTts2BbL1-GoOgmEpbSFwKN2aLb5oQt6EYKCnv87d2PgKS_hz5fnV66hYnCYhk3sLpR92nqCqLcPyMU2sfnJzK2OQ-CNR7OBasb8Dkf5sWo4ZMBNTnK6)
> _Link styles after_
> 
> **Link:** colour NHS blue with an underline
> **Hover:** colour NHS dark pink with affordance of no underline and pointer cursor
> **Focus:** colour NHS black, background colour NHS yellow and border bottom colour NHS black
> 
> ## User testing
> 
> ### What we were looking to learn:
> - Do the focus styles help users who rely on them
> - Do the focus styles hinder users who don’t rely on them
> 
> We recreated pages of the NHS website in a prototype and set the participants tasks, including seeking information (navigating through pages) and filling in a form.
> 
> ### Findings
> - All participants navigated with no problems
> - Participants who didn’t rely on focus styles didn’t notice them
> - Participants who relied on focus styles found them useful
> 
> #### Quotes
> 
> > “showing me where I am, that’s good”
> 
> ## What next 
> 
> We have more user testing scheduled in but considering our findings so far and the fact that our work is based predominantly on GOV’s work, we’re confident that the focus styles can go live.

Full document: https://docs.google.com/document/d/11AjdOgWC7ue1bit5AFyaneNwJYiudgLhf8nOxCWbn9M/edit#

**Comment by christopherthomasdesign** [comment] 2020-02-25 17:15
# Hover states

I've been doing a bit of exploration into this issue.

It's worth remembering that over 60% of GOV.UK users are on touch devices. So any work on hover states should only be seen as a small enhancement that acts as an extra affordance for mouse/trackpad users. It might be particularly helpful for people with cognitive impairments, low digital literacy or low vision.

I prototyped some different approaches to hover states, you can have a look at these in more detail here: https://design-system-mess.herokuapp.com/ (username:design / password:mess)

## Removing or adding underlines

I started with an approach similar to the NHS example above – "if there is an underline, remove it; if there is no underline, show one". This ran into problems when using links on dark backgrounds, like in an [interruption card](https://github.com/alphagov/govuk-design-system-backlog/issues/27) (this component isn't currently in the Design System but many teams use it and it probably will exist in the future). If your link colour is the same as the text colour, and you remove the underline on hover, you lose the visual differentiator and it becomes unclear what you're selecting:

### Link
<img width="627" alt="Screenshot 2020-02-25 at 14 45 45" src="https://user-images.githubusercontent.com/19834460/75268904-04a65a80-57f0-11ea-90a2-55d38540288a.png">

### Hover
<img width="628" alt="Screenshot 2020-02-25 at 14 45 54" src="https://user-images.githubusercontent.com/19834460/75268934-0a03a500-57f0-11ea-81e3-9b5aa1473e9f.png">

You can help this by using a tint of the original colour on hover. But then you run into the same problem we were trying to solve – the tint won't be distinct enough from the original link. I like the idea of *not* changing the colour on hover as a rule, and using a different visual change instead. It means that if your original link style is obviously a link and has enough colour contrast, the hover state will too.

## Changing underline styles

An experiment I quite liked was using a thicker border on hover. I  used an adapted version of the focus state styling, with a transparent background and the border at the bottom taking the same colour as the text:

### Link
<img width="651" alt="Screenshot 2020-02-25 at 10 56 03" src="https://user-images.githubusercontent.com/19834460/75268995-24d61980-57f0-11ea-8e83-102f22331322.png">

### Hover
<img width="655" alt="Screenshot 2020-02-25 at 10 56 11" src="https://user-images.githubusercontent.com/19834460/75269006-2a336400-57f0-11ea-962e-e2a75e09f135.png">

### Focus
<img width="652" alt="Screenshot 2020-02-25 at 17 00 03" src="https://user-images.githubusercontent.com/19834460/75269124-4fc06d80-57f0-11ea-8872-a41aa98f13d4.png">

Clearly, the hover and focus states may be indistiguishable to users with certain visual impairments, or using screens that don't show certain colours very well. However I *think* there are two changes in state that are particularly important:

* Link —> Focus (for keyboard users)
* Link —> Hover (for mouse users)

At the moment I'm not sure how different the hover and focus states need to be from one another.

There’s the possibility that someone might navigate with both a keyboard and a mouse. Or with the mouse pointer left idle on the screen whilst tabbing through – that could make it unclear if a hover and a focus were showing at the same time. But not sure how common this is or what the impact would be. Any input on this would be appreciated.

## Next steps

Would be great to get any feedback on the ideas here or examples of how others have approached this.

Will also try and get something like this example into some user research to see how it tests. Let me know if you've got any research coming up and would like to add some new hover states into your prototypes.

**Comment by nickcolley** [comment] 2020-02-27 13:27
We should also test what these different states look like cross browser/ operating system.

**Comment by hannalaakso** [comment] 2020-07-06 14:29
We received some useful feedback from the Working Group for [making hover styles clearer](https://github.com/alphagov/govuk-design-system/pull/1274) and will do some exploration to answer their questions. 

[Link to WG feedback summary when it's posted]

## Why
New hover styles could be a breaking change for some users so we want to use the feedback from the WG to ensure that the hover styles work for different edge cases.

## Done when
- [ ] We have considered how the WG feedback should be reflected in the hover styles and have created some mock styles, if appropriate

We have tested how the hover styles work for:
- [ ] Text blocks eg. gov.uk figures
<img width="200" alt="text blocks with figures on gov.uk" src="https://user-images.githubusercontent.com/5007934/86380428-f4adf400-bc83-11ea-9890-24750d064629.png">

- [ ] Text blocks with icons eg. Bank Holiday page links
<img width="250" alt="text block links on gov.uk bank holiday page" src="https://user-images.githubusercontent.com/5007934/86380659-435b8e00-bc84-11ea-8c60-83ef19adde3d.png">

- [ ] Images as links
- [ ] White backgrounds and non-white backgrounds (already done but we should check this if we change anything)
- [ ] Other cases - add here 

As indicated to the WG, we also have post-review actions to:
- [ ] Consider [touch highlights](https://github.com/alphagov/govuk-frontend/issues/1205)
- [ ] Test if colour for the underline can be inherited from the text colour
- [ ] Test in different browsers/devices

We should also:
- [ ] Decide if we want to create a proposal for the changes, and create a new card if appropriate
- [ ] Decide if we want to do a pre-release of the work, and create a new card if appropriate

**Comment by hannalaakso** [comment] 2020-07-07 16:34
We received some useful feedback from the Working Group for [making hover styles clearer](https://github.com/alphagov/govuk-design-system/pull/1274) and will do some exploration to answer their questions. 

[Summary of Working Group feedback](https://github.com/alphagov/govuk-frontend/issues/1417#issuecomment-654273692)

## Why
New hover styles could be a breaking change for some users so we want to use the feedback from the WG to ensure that the hover styles work for different edge cases.

## Done when
- [ ] We have considered how the WG feedback should be reflected in the hover styles and have created some mock styles, if appropriate
- [ ] We have considered if style could cause movement sickness or negatively impact how content is scanned

We have tested how the hover styles work for:
- [ ] Text blocks eg. gov.uk figures
<img width="200" alt="text blocks with figures on gov.uk" src="https://user-images.githubusercontent.com/5007934/86380428-f4adf400-bc83-11ea-9890-24750d064629.png">

- [ ] Text blocks with icons eg. Bank Holiday page links
<img width="250" alt="text block links on gov.uk bank holiday page" src="https://user-images.githubusercontent.com/5007934/86380659-435b8e00-bc84-11ea-8c60-83ef19adde3d.png">

- [ ] Images as links
- [ ] White backgrounds and non-white backgrounds (already done but we should check this if we change anything)
- [ ] We have considered whether style could cause movement sickness or make it harder to scan content

As indicated to the WG, we also have post-review actions to:
- [ ] Consider [touch highlights](https://github.com/alphagov/govuk-frontend/issues/1205)
- [ ] Test if colour for the underline can be inherited from the text colour
- [ ] Ensure the style is tested in [browsers we support](https://github.com/alphagov/govuk-frontend#browser-and-assistive-technology-support) 

We should also:
- [ ] Decide if we want to create a proposal for the changes, and create a new card if appropriate
- [ ] Decide if we want to do a pre-release of the work, and create a new card if appropriate

**Comment by MalcolmVonMoJ** [comment] 2020-07-14 12:54
I just looked at [this in the preview](https://github.com/alphagov/govuk-frontend/issues/1417) and the underline seems to almost touch the following line (Win 10 & Google Chrome).  The focus state doesn't have this issue.  Maybe adding a white background will sort the issue in a similar way.
![image](https://user-images.githubusercontent.com/32877315/87427889-5e5dc480-c5d9-11ea-8d81-493f25d14d40.png)

**Comment by nnagewad** [comment] 2020-10-07 14:02
# Hover state for white text behind coloured background

## Background:
Over on GOV.UK we needed to address the hover state for white text behind a coloured background.

The situation arose on the [COVID-19 page](https://www.gov.uk/coronavirus), where it was noticed that the `action link` on the page's header doesn't have a hover state.

Rather than find a solution for this one scenario, is there a solution that works throughout GOV.UK?

### Coronavirus Header
![c19_header](https://user-images.githubusercontent.com/8485154/95340730-6910b880-08ad-11eb-8e94-e2e78ca0985c.png)

## Discovery:
When hovering over a white text behind a coloured background the colour of the text will change from **govuk-colour("white")** = `#FFFFFF` to `#DDDCDB`.

This colour was discovered when experimenting the limits of adding shade/darkening the white text, all the while complying with a11y standards of **4.5:1** colour contrast ratio, the AA grade for font-sizes that is less than `19px`.

Experimentation/Discovery was made in this [Figma file](https://www.figma.com/file/BJBSVtwDgdZPOfQnf3kimJ/Exploration?node-id=67%3A2)

## Initial implementation
Update will be made to the `action link` GEM as per solution to prompt conversation with the front-end community within GOV.UK.

## Next steps
See what feedback is within the community, based on that we can roll it out throughout GOV.UK

**Comment by chris-gds** [comment] 2020-10-12 09:48
[Related PR](https://github.com/alphagov/govuk-frontend/issues/1417) raised

**Comment by 36degrees** [comment] 2021-01-27 09:59
Browser support for `text-decoration-thickness` has improved since we first started looking at this – technically it's been in Chrome and Edge since v87 and Opera since v73, but [there's a bug in Chromium that means it doesn't work unless either `text-underline-offset` is set to something other than `auto` or `text-decoration-color` is set to something other than `currentColor`](https://crbug.com/1154537).

It looks like that issue should be fixed in Chrome 90, which [becomes stable in April](https://chromiumdash.appspot.com/schedule). As Edge and Opera are both built on top of Chromium, I'd expect both of those browsers to be updated with the same fix not long after.

Using text-decoration-thickness would allow us to do something like this, if we wanted:

https://user-images.githubusercontent.com/121939/105970532-61099e00-6081-11eb-9ecc-345c13bf196b.mov

It would need to be considered an enhancement as it would not work in IE11, Edge < 90 Early 2021), Chrome < 90 (April 2021), Safari < 12.1 (March 2019), Firefox < 70 (October 2019) – unless we also set the color or offset.

**Comment by christopherthomasdesign** [comment] 2021-02-04 16:13
## New link styles and hover states

I've been doing some more work on links, building on Ollie's work above. I'm trying to solve two problems here:
- link hover states are not clear
- link text is not easy enough to read – especially when used in long lists or at larger sizes (a problem raised by designers on the GOV.UK team)

The increasing support for a few CSS properties means we can now control more about how links look. I've had a go at making links that:
- are visually lighter
- place the underline a decent distance from the baseline of the text (far enough to interfere less with the words, close enough that it's clearly identified with them)
- have a clearer hover state

It's worth reiterating that these changes should be seen as an enhancement. For browsers that don't support some or all of these properties, the normal underline will still work.

### Proposed design

Look at the work in Frontend at https://github.com/alphagov/govuk-frontend/pull/2089. Still some details to iron out, but something like this.

Before:

<img width="651" alt="Screenshot 2021-02-02 at 10 40 49" src="https://user-images.githubusercontent.com/19834460/106919594-33b49400-6702-11eb-8eab-2dfc8dfe8551.png">

After:

<img width="657" alt="Screenshot 2021-02-02 at 10 40 56" src="https://user-images.githubusercontent.com/19834460/106919650-3fa05600-6702-11eb-8314-39c2fedddb46.png">


I've added the following CSS to links:

```
text-decoration-thickness: 1px;
text-underline-offset: .1em;
text-decoration-color: govuk-colour("light-blue");
```

It makes all link underlines 1px thick, sits them a bit further below the baseline of the text, and uses a lighter shade of blue to make the line a bit visually lighter.

For the hover state, I made the line thicker and brought back the original link colour to make it stronger:

<img width="677" alt="Screenshot 2021-02-02 at 10 46 07" src="https://user-images.githubusercontent.com/19834460/106919928-7b3b2000-6702-11eb-9134-20b002506cde.png">

```
text-decoration-thickness: unquote("max(2px, .18em)");
text-decoration-color: $govuk-link-colour;
```
Here's how that scales for different sized text:
<img width="649" alt="Screenshot 2021-02-04 at 16 07 07" src="https://user-images.githubusercontent.com/19834460/106920530-17fdbd80-6703-11eb-8a9c-44fd26350fcb.png">

Hover:
<img width="653" alt="Screenshot 2021-02-04 at 16 07 13" src="https://user-images.githubusercontent.com/19834460/106920554-1d5b0800-6703-11eb-9b4b-352e0a022f4c.png">

### Considerations

#### Different coloured links and backgrounds

The use of `govuk-colour("light-blue")` for underlines works well for blue links on white backgrounds, but obviously wouldn't work on darker backgrounds. Part of the rationale for using thicker underlines for hover states to make them more flexible for different backgrounds because they don't use a colour other than the link colour. So we should see if there's a more flexible way to do the underline colour tint. You can't use SASS tint functions on `currentColor`, and I don't think you can set an opacity on an inherited underline colour either...

I think we'd want to be fairly confident that any underline colour has at least 3:1 contrast with the background to pass [1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html).

If something like that's not possible, we could either: 
- just use the inherited link text colour and lose the (probably small) benefit of a lighter underline
- add specific underline styling to all the other kinds of links we support (e.g. error summary, green notification banner)

#### Distance from the baseline

For some reason, every browser's implementation of `text-underline-offset` is different. Not massively, probably not critically.  

On all browsers, the combination of `text-underline-offset` + `text-decoration-thickness` together means that when you hover and make the underline thicker, it moves slightly lower down from the text. I don't really see that as a problem but would be interested to hear if others do.

Another thing we could look at doing is making the underline offset on hover the same distance from the baseline as our focus state border. Again, I don't think there are huge gains here but it might look a bit more elegant or less jumpy.

#### Testing across browsers and versions

I've done a bit of this but it would be good to test a bit more thoroughly on different versions and devices.

**Comment by christopherthomasdesign** [comment] 2021-03-23 11:54
We sent the revised implementation of link styles and hover states to the working group in March 2021.

The group **approved** the changes, with the following main feedback:

- consider the hover state for visited links and whether they should change colour
- make sure the hover underline widths aren’t too heavy, and double-check the width across browsers

We'll need to do a little bit more exploration to address these, covered in https://github.com/alphagov/govuk-design-system/issues/1578

**Closed** 2021-05-05 12:08 UTC
Labels: accessibility, audit may 2019, design, typography
