### ISSUE TITLE
User Not Informed of Additional Content JAWS

### ISSUE THREAD

**Issue by Dawdre** [alphagov/govuk-frontend#1951] opened 2020-09-09 14:52 UTC
It appears JAWS has issues with conditionally hidden content. NVDA screen reader works fine when calling out the hidden content inside. A 3rd party test was carried out on one of our applications recently.

Environment:
Windows 10 – Internet Explorer 11 - JAWS

Is this an issue that is known about?

**Comment by 36degrees** [comment] 2020-09-09 15:16
Hi @Dawdre,

I believe this is a duplicate of #935 – can you take a look at that issue and see if it describes what you're seeing?

Thanks.

**Comment by 36degrees** [comment] 2020-10-09 08:21
I'm going to close this based on my previous message, but if you believe this is a separate issue please feel free to reply and we can re-open this.

**Closed by 36degrees** 2020-10-09 08:21 UTC
