### ISSUE TITLE
Update our internal documentation on polyfilling

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-frontend#3722] opened 2023-05-30 15:43 UTC
## What

Update our [polyfilling doc](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/polyfilling.md)

## Why

Previously, we used the polyfill.io service to generate polyfills and detect the need for them. We will likely move to transpiling our code, and automatically polyfilling missing APIs in older browsers. Our documentation should be updated to reflect this new process.

## Who needs to work on this

Developers, Technical writer

## Who needs to review this

Developers, Technical writer

## Done when

- [ ] Our polyfilling documentation reflects our chosen method for polyfilling

**Comment by romaricpascal** [comment] 2023-07-20 11:43
Would be great to make sure we document the different parts around the transpilation (and not just the polyfilling): the tools (browserslist, Babel) as well as stuff like [Babel's mapping from browser to transforms that need applying ](https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json) to help look things up if we get reports of stuff not working in a specific browser.

**Comment by romaricpascal** [comment] 2023-07-20 11:45
Also noting that this issue is closely linked with (duplicate of, even, maybe) https://github.com/alphagov/govuk-frontend/issues/2159

**Comment by 36degrees** [comment] 2024-01-19 10:58
Although the documentation is rather terse, I think it meets the 'done when' for this issue ('Our polyfilling documentation reflects our chosen method for polyfilling') so I'm going to call this done.

We can revisit as our approach to polyfilling evolves.

**Closed by 36degrees** 2024-01-19 10:58 UTC
Labels: documentation, javascript
