### ISSUE TITLE
Checkboxes component incorrectly hides elements in certain cases

### ISSUE THREAD

**Issue by bilbof** [alphagov/govuk-frontend#1142] opened 2019-01-16 10:48 UTC
The [Checkboxes component](https://github.com/alphagov/govuk-frontend/blob/master/src/components/checkboxes/checkboxes.js) adds the css class `govuk-checkboxes__conditional--hidden` to unrelated checkboxes in certain cases.

We found this in `finder-frontend` so have patched it for that repo there (see https://github.com/alphagov/finder-frontend/pull/782) but this could affect others.

### Description of issue

From a quick investigation it looks like the following is happening:

The `handleClick` event calls `setAttributes` with `event.target` as the `$input` argument. However, if jQuery `click` or `trigger('click')` is used, following a click event on a different element, then the `event.target` is the element clicked by the user, not the checkbox. This is a problem because `govuk-checkboxes__conditional--hidden` will then be added to the clicked element, not a checkbox.

Example pseudocode.

```
<checkbox>
<div class='uncheck-checkbox'>Uncheck box</div>
<script>
$('.uncheck-checkbox').on('click', () => {
    $('checkbox').trigger('click');
})
</script>
```

When the div is clicked, then this will hide the div. I haven't tested this in isolation, but I think this is the case given that removing the click event in https://github.com/alphagov/finder-frontend/pull/782 was able to fix this issue for us.

**Comment by nickcolley** [comment] 2019-01-16 11:07
Hey @bilbof,

I'm trying to put together something to reproduce this but I'm not sure I'm able to replicate what you describe:

https://govuk-frontend-issue-1142.glitch.me/ (https://glitch.com/edit/#!/govuk-frontend-issue-1142?path=src/views/index.html:21:10)

Could you [remix this example](https://glitch.com/edit/#!/remix/govuk-frontend-issue-1142) and give explicit step by steps for how to reproduce this, including what happens and what you expected to happen please?

**Comment by andysellick** [comment] 2019-01-21 17:00
I think this is a duplicate of https://github.com/alphagov/govuk-frontend/issues/1153

**Closed** 2019-01-23 13:01 UTC
Labels: investigation, submitted-by-user
