### ISSUE TITLE
Can we make it an easier user experience when beforeContent is empty?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-frontend#888] opened 2018-07-12 11:19 UTC
In this situation, the spacing at the top of the page is wrong.

The current solution is to add this to your page:

```{% set mainClasses = "govuk-main-wrapper--l" %}```

Wondering if we can do anything that makes this simpler/clearer or that, ideally, our users don't need to do anything

**Comment by joelanman** [comment] 2018-07-12 11:20
We could make the beforeContent block have default content that would provide the correct spacing:

```{% block beforeContent %}<div class="empty-before-content"></div>{% endblock %}```

**Comment by nickcolley** [comment] 2018-07-12 11:23
If we contributed the 'self' feature to the Nunjucks project we could do this in a non-hacky way:

https://github.com/mozilla/nunjucks/issues/164

**Comment by 36degrees** [comment] 2019-05-20 10:22
I wonder if we could do this in CSS instead, perhaps by applying an additional margin to main if it's the `:first-child` (and thus has no preceding siblings)

**Comment by joelanman** [comment] 2019-05-21 10:08
Is this arguably a bug, if a user doesn't know to do the 'right' thing, it will be wrong?

**Comment by nickcolley** [comment] 2019-05-21 10:21
We can definitely make it better and I hope we do, but the current feature works as we designed it to, so it's not a bug.

**Comment by 36degrees** [comment] 2019-06-07 14:29
I believe this was addressed in #1371, so I'm going to close it.

**Closed by 36degrees** 2019-06-07 14:29 UTC
Labels: Effort: hours, Enhancement: feature-request, Priority: low
