### ISSUE TITLE
Summary List Macro - Using Span when there are no actions

### ISSUE THREAD

**Issue by Cavalier07** [alphagov/govuk-frontend#1998] opened 2020-10-27 11:30 UTC
Hi,

Using v3.7.0 of the Summary List nunjucks macro. We get the following error on the Axe Accessibility tool:

`<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements`

It is caused by an empty span tag when there are no actions for a particular row. Is there any way this can be removed/changed so we adhere to the html validation in Axe

Thanks,
Tom

**Comment by 36degrees** [comment] 2020-10-27 11:34
Hi @Cavalier07,

I believe this is a duplicate of #1806 – are you happy that's the same problem you're seeing?

**Comment by Cavalier07** [comment] 2020-10-27 11:36
Yes that's the same problem. Can we close this as a duplicate.

**Comment by 36degrees** [comment] 2020-10-27 11:37
Thanks for taking the time to report it anyway, Tom 🙂 

Please feel free to add any additional comments to the original issue – you can also subscribe to notifications on that issue so that you'll be notified when it's fixed.

**Closed by 36degrees** 2020-10-27 11:37 UTC
