### ISSUE TITLE
Details component enter key only fires in IE if contained within a form

### ISSUE THREAD

**Issue by frankieroberto** [alphagov/govuk-frontend#1558] opened 2019-09-06 14:37 UTC
If you focus on the `<details>` element on https://design-system.service.gov.uk/components/details/default/index.html within Internet Explorer (eg IE11) and then press [Space] or [Enter], the component opens/closes.

However, if the `<details>` element is _not_ contained within a `<form>` element (as it is on that example page), then only the [Space] key works, but not the [Enter] key.

This seems to be down to a longstanding bug/feature within Internet Explorer which is that [Enter] keypress do not fire on elements (other than buttons) unless they are contained within a form. See [conversation on this bug reported to angular.js](https://github.com/angular/angular.js/issues/11287).

Possible fixes:

* Wrap each `<details>` element in a `<form>` element. Not ideal, as you'd have to only do this if it wasn't already within a form.
* Add some logic within the [handle inputs polyfill](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/details/details.js#L114-L145) to fire the `click` event from within the `keyup` listener (but only if not already fired from the `keypress` listener).

**Comment by kellylee-gds** [comment] 2019-09-11 13:20
Agreed at triage to timebox investigation to half day.

**Comment by nickcolley** [comment] 2020-01-27 11:14
OK I've managed to make a minimum reproduction.

I think the `<form>` element is important here so thanks for raising that.

- [Minimal example with button next to details within a form](https://govuk-frontend-issue-1558.glitch.me/?form=true)
- [Minimal example with button next to details](https://govuk-frontend-issue-1558.glitch.me)

My current thinking is that the buttons on the page turn the document/body into the 'form' since there's no form around those buttons which interferes with the event listeners in the details component.

Since the keyup eventlistener is not called at all when the button is on the page.

Will update if I figure anything out.

**Comment by nickcolley** [comment] 2020-01-27 11:29
@frankieroberto thanks for raising this with great steps to reproduce, I don't think this is something that we can fix our end so I will close this but if you (or anyone else) knows of a way we could avoid this behaviour in Internet Explorer 11 we'd love to hear it.

**Closed by nickcolley** 2020-01-27 11:29 UTC
Labels: Effort: hours, Priority: low, investigation
