### ISSUE TITLE
Allow for smaller form fields

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-frontend#395] opened 2017-12-20 09:17 UTC
Some user interfaces are designed for high information density and regular use. In these cases, smaller form controls may be required.

The Home Office design system already has small versions of [radio buttons](https://home-office-digital-patterns.herokuapp.com/components/radios) and [checkboxes](https://home-office-digital-patterns.herokuapp.com/components/checkboxes), we should probably add text fields, select boxes and buttons to that list.

Implementation considerations:

- is this a modifier class that you can apply to any form component?
- does the class apply to all form elements inside the component?
- for text input and select, does the font get smaller too?

**Comment by nickcolley** [comment] 2017-12-20 10:42
If our components are built in a way that means they're using relative units, you could in theory do this fairly easily.

From an email chain around if we should use REM/EM/PX

"
http://jsbin.com/zixihajisi/1/edit?html,css,output

Using BEM terminology.

The top level 'Block' has REM with PX fallback.

The 'Elements' should use EM. (In this case it's the arrow and borders that are relative.)

'Modifiers' use REM with PX fallback to make small / big variants of the component

The root page font size can then also size these components when using REM (or PX with a build step)

With this approach (as seen in the demo above) to make a small version of the button we only have to add different font size to the top level.
"

**Comment by joelanman** [comment] 2017-12-20 16:00
if we did this, we could make sure they go back to full size on small screens, so they remain easy to use with touch

**Comment by nickcolley** [comment] 2018-05-02 11:16
Duplicate of https://github.com/alphagov/govuk-design-system-backlog/issues/121

**Closed by nickcolley** 2018-05-02 11:16 UTC
Labels: new feature
