### ISSUE TITLE
All sentences should be inside <p> (or the relevant semantic elements)

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-frontend#1611] opened 2019-10-11 11:45 UTC
I'm going to add a few points that came out of a recent developer review, before three of our services are sent for an external accessibility audit.

### Inset text and Panel components
We're currently using the `govukInsetText()` and `govukPanel()` macros and we've been flagged during a developer review for putting text inside `<div>` tags.

All three services were caught out by this.

The non-semantic HTML is the recommended usage on the GOV.UK Design System examples shown here:

https://design-system.service.gov.uk/components/inset-text/
https://design-system.service.gov.uk/components/panel/

You can see in these screenshots:

![Inset text](https://user-images.githubusercontent.com/415517/66648305-24632a80-ec23-11e9-8fa0-17627317eeb0.png)
![Panel](https://user-images.githubusercontent.com/415517/66648307-24632a80-ec23-11e9-9119-df05dd82e050.png)

Since other service teams may copy from the examples and make the same mistakes as us, I'd prefer it if the examples included semantic HTML by default! 😊 

Suggested change:

**Before**
```js
{{ params.html | safe if params.html else params.text }}
```

**After**
```js
{% if params.html %}{{ params.html | safe }}{% else %}<p>{{ params.text }}</p>{% endif %}
```

But other macros might be affected too.

It's been raised before in https://github.com/alphagov/govuk-design-system/issues/822

Thanks

**Comment by nickcolley** [comment] 2019-10-11 11:47
Pre-triage comment: I believe that there are other components we'd want to review as part of considering this.

**Comment by colinrotherham** [comment] 2019-10-11 12:05
Sorry just realised we're flagged on one service only with **warning text**.

I'd expect a wrapping paragraph tag here too.

![Warning text](https://user-images.githubusercontent.com/415517/66650144-cbe25c00-ec27-11e9-8918-28d20f5a1004.png)

Thanks @nickcolley.

**Comment by hannalaakso** [comment] 2019-10-23 15:36
@colinrotherham We'd be interested in hearing whether this gets flagged in your external accessibility audit.

Have added this to 4.0 milestone as this would be a breaking change.

**Comment by adamliptrot-oc** [comment] 2020-02-06 17:48
WHATWG deem the`<p>` element as only one way of markup up a paragraph. Semantically it seems not to have any impact. There could be styling implications of course.
https://html.spec.whatwg.org/multipage/dom.html#paragraph

**Comment by nickcolley** [comment] 2020-02-07 13:57
Thanks @adamliptrot-oc, that's good context, I've had a chat about this with some people on the team...

We're going to close this for now as we want to avoid breaking changes unless it's necessary, but we're happy to revisit this again if we become aware of any real-world issues caused by the lack of `<p>` tags.

**Closed by nickcolley** 2020-02-07 13:57 UTC
Labels: Effort: days, Enhancement: feature-request, Priority: low, breaking-change
