### ISSUE TITLE
File upload component not picked up by dragon on IE11

### ISSUE THREAD

**Issue by nehakannaujia1** [alphagov/govuk-frontend#2065] opened 2020-12-14 12:59 UTC
Component: https://design-system.service.gov.uk/components/file-upload/

Voice command tool dragon doesn't click on "Upload a link" input field on IE11. Though its working fine on chrome. Here is how it looks on IE - 
![image](https://user-images.githubusercontent.com/50657531/102083789-04715d00-3e0c-11eb-8e00-bcb694fd559f.png)

**Comment by hannalaakso** [comment] 2020-12-17 12:38
Thanks for reporting this @nehakannaujia1 👍  We know that the [native file upload element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) when used with Dragon is generally buggy and we've previously reported this to Nuance: https://github.com/alphagov/reported-bugs/issues/35. 

So it's likely that the issue is not with the Design System file upload component but Dragon when operating the native file upload element. 

However we're going to do a bit more digging into this since you reported that the component works in Chrome whereas as discussed in the above issue we haven't found this to be the case. I'm leaving this issue open for any follow up findings or comments.

**Comment by hannalaakso** [comment] 2021-01-14 09:24
@nehakannaujia1 We've re-tested the native file upload element in Chrome with Dragon. As previously reported to Nuance (alphagov/reported-bugs#35), we're still unable to click the button using the voice control commands. The commands tried were:
* 'click choose file'
* 'click upload a file'
* 'click file'
* 'click choose'
* 'click button'
* 'click upload'

As explained in my above message, we believe that that the native file upload element is generally very buggy in Dragon and that this isn't an issue with the Design System file upload component. 

However, if you have been able to use the file upload component successfully in Chrome, we would be interested in hearing what voice command you used and what version of Dragon this was on.

**Comment by edwardhorsford** [comment] 2021-01-18 13:44
@hannalaakso did you try with mousegrid or the numbered entry mode?

**Comment by hannalaakso** [comment] 2021-01-18 15:07
Thanks for your comment @edwardhorsford 👍 This bug happens in the dictation mode in Dragon. Navigating by mousegrid works (see [bug report](https://github.com/alphagov/reported-bugs/issues/35)). Is the 'numbered entry mode' the mousegrid as well?

**Comment by nehakannaujia1** [comment] 2021-02-12 12:49
@hannalaakso : I used the "Upload a file" command which is the label for the field and it opened the file dialogue of the window on chrome.

**Comment by hannalaakso** [comment] 2021-04-07 12:23
@nehakannaujia1 Apologies for the delay. Which version of Dragon and Chrome were you using? What operation system and version of it were you using? Was the complete voice command you used 'click upload a file'? 

We tested in Dragon Professional 15 and Chrome 87 on Windows 10 and were not able to select the file input - results [here](https://github.com/alphagov/govuk-frontend/issues/2065#issuecomment-760070675).

**Comment by nehakannaujia1** [comment] 2021-04-07 12:46
@hannalaakso  :  yes I use "click upload" and the combinations "click upload a file". I used windows 10 but not sure bout the dragon and chrome version its been a while since I tested it. But definitely it was higher or version 15 for dragon and chrome also the latest.

**Comment by hannalaakso** [comment] 2021-04-07 15:47
@nehakannaujia1 Thank you. Would you be able to add a comment to https://github.com/alphagov/reported-bugs/issues/35? If you were able to find out the version of Dragon and include that in the comment it would be really useful. I'd like to close this issue as there is no bug to fix here on the Design System component.

**Comment by hannalaakso** [comment] 2021-04-14 17:17
@nehakannaujia1 I've added a comment on your behalf to https://github.com/alphagov/reported-bugs/issues/35#issuecomment-819683079 (excluding the version of Dragon that was used).

**Closed by hannalaakso** 2021-04-14 17:17 UTC
Labels: file upload, 🐛 bug
