### ISSUE TITLE
<Select> elements background color in Ubuntu

### ISSUE THREAD

**Issue by LucaDelBuonoHMCTS** [alphagov/govuk-frontend#1659] opened 2019-11-20 12:31 UTC
`<select>` elements in Ubuntu render with a grey background.

Chrome:
![dropdown](https://user-images.githubusercontent.com/42244677/69239371-f235d880-0b91-11ea-9a4e-edea43808eb2.png)

Firefox:
![dropdown_ff](https://user-images.githubusercontent.com/42244677/69239384-f95ce680-0b91-11ea-8e1d-fc73d941b876.png)

Can a `background-color: white` be added to the next version of GDS please?

**Comment by terrysimpson99** [comment] 2019-11-21 16:16
![Screenshot_20191121-160522_Opera (2)](https://user-images.githubusercontent.com/48089049/69355190-4798e500-0c79-11ea-9a00-f576f9ed9285.jpg)

I think this is a similar issue to what happens on Android 8.0.0, Opera 54.3

Hope that helps.

**Comment by hannalaakso** [comment] 2019-11-25 18:48
Hi @LucaDelBuonoHMCTS 

Thanks for raising this. The reason we don't set the background colour of `<select>` is that when [users change colours in the browser](https://accessibility.blog.gov.uk/2018/08/01/supporting-users-who-change-colours-on-gov-uk/), with certain types of colour combinations the text becomes invisible in Firefox. 

There is an [issue raised about this](https://bugzilla.mozilla.org/show_bug.cgi?id=1335476) on the Firefox backlog.

Here's a gif of the GOV.UK Frontend select following the steps to reproduce given in the above issue.

![500](https://user-images.githubusercontent.com/5007934/69568540-b779d900-0fb3-11ea-8588-762d5ffe7fd7.gif)
 
With this in mind I'm going to close this issue. However we would consider doing this if we had evidence that the related bugs had been fixed by browser vendors.

**Closed by hannalaakso** 2019-11-25 18:48 UTC
Labels: Enhancement: feature-request
