### ISSUE TITLE
Warning text does not support multi-line

### ISSUE THREAD

**Issue by Jamesking56** [alphagov/govuk-frontend#3868] opened 2023-06-28 13:33 UTC
## Description of the issue

https://design-system.service.gov.uk/components/warning-text/

The warning text component does not support text that drops onto multiple lines

## Steps to reproduce the issue

The icon looks a bit strange when the element is showing multiple lines of information

```html
<div class="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Notice</span>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias dolores illo praesentium, quaerat ratione reiciendis voluptas. Corporis, delectus, enim error et illum maxime, officiis quam qui quibusdam repudiandae tempora?
    </strong>
</div>
```

## Actual vs expected behaviour

![image](https://github.com/alphagov/govuk-frontend/assets/253237/9e456700-8480-4463-b770-6e7e0a1872a8)

**Comment by 36degrees** [comment] 2023-06-28 16:02
Hi @Jamesking56,

Can you elaborate on what you mean 'the icon looks a bit strange'? As far as I can tell from your screenshot this is working as designed.

**Comment by Jamesking56** [comment] 2023-06-28 16:04
> Hi @Jamesking56,
> 
> Can you elaborate on what you mean 'the icon looks a bit strange'? As far as I can tell from your screenshot this is working as designed.

It looks high up stuck in the top left?

**Comment by Jamesking56** [comment] 2023-06-29 10:13
> This is currently working as designed – there was [a change made back in 2019](https://github.com/alphagov/govuk-frontend/pull/1578) to vertically align the icon with the first line of the text:
> 
> > The primary purpose of the this PR was to align the icon with the top line, so that when the content wraps the icon doesn't vertically align with the entire block and potentially end up out of sight when the user starts reading the warning text.
> 
> Have you seen any evidence that users are confused by this? What would you expect the component to do when there are multiple lines of text?

I would expect it to look like this:

![](https://user-images.githubusercontent.com/23356842/65227812-37ba2480-dac1-11e9-8e69-51ed47e3cfc9.png)

I haven't seen evidence of user confusion but if there was text above that isn't included in the warning, wouldn't the high up icon then cause confusion which parts of the text it is for?

**Comment by querkmachine** [comment] 2023-06-29 10:31
Having the icon vertically centred is fine if you assume a certain quantity of text and a certain amount of horizontal space. It starts to quite goofy in situations where those circumstances are not ideal—such as on mobile devices or for users who use zooming or magnification tools for accessibility purposes. 

<img width="283" alt="image" src="https://github.com/alphagov/govuk-frontend/assets/1253214/e21ef1ee-efdb-440b-a271-78cb377d6bb6">

**Comment by christopherthomasdesign** [comment] 2023-07-06 13:05
Hi @Jamesking56 

Thanks for raising this, you're not the first to bring it up!

We placed the icon at the top left because it ensures the warning icon is within the path of people using screen magnification tools. The icon is important for understanding that the text is a warning, and not just some bold text. For longer blocks of warning text, you could miss that context.

I personally agree that it looks a bit strange when it sticks out above the top of a large block of text. I think ideally it'd be vertically centre-aligned when there's just one line of text, and aligned to the top of the text block when it runs over 2 or more lines. But we're not aware of a way to do this reliably in CSS. So we decided the accessibility consideration trumped the aesthetic one in this case.

Hope that makes sense.

**Comment by Jamesking56** [comment] 2023-07-09 22:41
@christopherthomasdesign Excellent explanation! I agree accessibility should triumph here :+1:

**Comment by querkmachine** [comment] 2023-07-10 09:03
@Jamesking56 Given the information above, are you happy for us to close this issue?

**Comment by Jamesking56** [comment] 2023-07-10 09:19
> @Jamesking56 Given the information above, are you happy for us to close this issue?

Yes can be closed

**Closed** 2023-07-10 10:21 UTC
Labels: 🐛 bug, awaiting triage, warning text
