### ISSUE TITLE
tab component issue

### ISSUE THREAD

**Issue by shiromi** [alphagov/govuk-frontend#1961] opened 2020-09-18 08:04 UTC
when I added tab component into my project ,tab navigation behaviors is odd when you refresh / page reload. like it's always flickering the first tab and then focusing the current tab. There is a delay to focus on current tab, it's focusing first tab always and then move to the current tab, this delay you can see when you refresh or reload the page. can anyone have a looking to this issue? any suggestion?

**Comment by hannalaakso** [comment] 2020-09-22 14:50
@shiromi Thanks for flagging this. 

Unfortunately we haven't been able to replicate the issue you've described. Could you please check if you can see the same behaviour on [our tabs example](https://design-system.service.gov.uk/components/tabs/default/index.html)? 

Could you also confirm what browser/device you're seeing this issue on?

**Comment by shiromi** [comment] 2020-09-22 15:51
> @shiromi Thanks for flagging this.
> 
> Unfortunately we haven't been able to replicate the issue you've described. Could you please check if you can see the same behaviour on [our tabs example](https://design-system.service.gov.uk/components/tabs/default/index.html)?
> 
> Could you also confirm what browser/device you're seeing this issue on?
@hannalaakso Thanks for looking at the issue,
Once we add above tab component on operational service we have the issue which I explained above. the issue is replicating when you reload the page. I have tested Chrome and Firefox browsers. if you have a time we can have a call so then I can show you the issue.

**Comment by hannalaakso** [comment] 2020-09-28 14:50
@shiromi Could you please email govuk-design-system-support@digital.cabinet-office.gov.uk so that we can find the best way of supporting you?

**Comment by shiromi** [comment] 2020-09-29 06:43
> @shiromi Could you please [contact us either via Slack or email](https://design-system.service.gov.uk/#support) so that we can find the best way of supporting you?

@hannalaakso 
shiromala.wanniarachchige@digital.hmrc.gov.uk
Thanks

**Comment by 36degrees** [comment] 2020-10-06 14:53
After catching up with @shiromi I believe we traced this back to some javascript in the service's application which saved the tab 'state' and restored it using an XHR request when the user returned to the page. The delay in the tab focus was caused by the time taken to make the XHR request to get the previous tab state.

I'm going to close this as I'm reasonably confident that the issue is not in GOV.UK Frontend. However, I've raised #1976 as it seems like it'd be useful to provide a mechanism for preserving tab state in the tabs component.

**Closed** 2020-10-06 15:02 UTC
Labels: tabs
