### ISSUE TITLE
govuk checkboxes component has invalid value set for test

### ISSUE THREAD

**Issue by kyle-bowden** [alphagov/govuk-frontend#2834] opened 2022-09-09 13:39 UTC
## Description of the issue
We have recently revised some of our patched tests in play-frontend-hmrc which integrate with govuk components. We have found an example that is missing a flag. The HTML [example](https://github.com/alphagov/govuk-frontend/blob/58a6edd1abdd461ab5a5e952daa921c5ebd1ce75/package/govuk/components/checkboxes/fixtures.json#L1292) specifies that the red item has a checked attribute but the first item for the checkbox should also then be marked as `"checked": true` [here](https://github.com/alphagov/govuk-frontend/blob/58a6edd1abdd461ab5a5e952daa921c5ebd1ce75/package/govuk/components/checkboxes/fixtures.json#L1275).

UPDATE

I found a few more examples that require the `"checked": true` property on the relevant item.

- [issue 1](https://github.com/alphagov/govuk-frontend/blob/58a6edd1abdd461ab5a5e952daa921c5ebd1ce75/package/govuk/components/checkboxes/fixtures.json#L27) 
- [issue 2](https://github.com/alphagov/govuk-frontend/blob/58a6edd1abdd461ab5a5e952daa921c5ebd1ce75/package/govuk/components/radios/fixtures.json#L438)
- [issue 3](https://github.com/alphagov/govuk-frontend/blob/58a6edd1abdd461ab5a5e952daa921c5ebd1ce75/package/govuk/components/radios/fixtures.json#L549)

## Environment (where applicable)

- GOV.UK Frontend Version: v4.3.1

**Comment by owenatgov** [comment] 2022-09-09 15:15
Hi @kyle-bowden. Thanks for raising this issue, however this behaviour is intentional.

These examples are intended to test the `values` attribute, which is an option at the root of the macro call that allows teams to set the checkbox values as a single array instead of using `checked`. You can read about it and how it interacts with the `checked` value on individual items in [the nunjucks macro guidance](https://design-system.service.gov.uk/components/checkboxes/#options-checkboxes-example--primary). This feature was introduced in https://github.com/alphagov/govuk-frontend/pull/2616

To illustrate this with the initial example, this scenario is codified in the [yml file containing the checkbox API docs](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/checkboxes/checkboxes.yaml#L905) and is used in the [associated test](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/checkboxes/template.test.js#L197). The intended behaviour here is that we can pass what is checked in the checkbox array via `values`, in this case `red` and `green`, but the intended behaviour is that the value of `checked`, if specified, overrides `values`.

With the above in mind, I'm going to close this issue. We hope you will consider contributing again in future.

**Closed by owenatgov** 2022-09-09 15:15 UTC
Labels: 🐛 bug, awaiting triage
