### ISSUE TITLE
govuk-file-url() cannot be overridden for use in Rails asset pipeline

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-frontend#728] opened 2018-05-29 16:29 UTC
From the spike GOV.UK has done into using GOV.UK Frontend they found that it's not possible to bring images in since they cannot use the asset pipeline functions required.

See https://github.com/alphagov/govuk_publishing_components/pull/328 for details.

**Comment by 36degrees** [comment] 2018-05-30 08:32
Closing as #730 is a duplicate of this, but has more detail.

**Closed by 36degrees** 2018-05-30 08:32 UTC
