### ISSUE TITLE
Media query with $until fails

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-frontend#1674] opened 2019-12-06 12:13 UTC
I think I have a bug with the media queries.

The following will not work:
<img width="616" alt="Screenshot 2019-12-06 at 10 24 36" src="https://user-images.githubusercontent.com/2204224/70322786-eea58100-1822-11ea-87f8-fda4565e36eb.png">

If I change to `$from: tablet` it's fine. Weirdly it doesn't cause a compiler issue -but the css doesn't seem to be output.

When trying with extend I get an error with the extend - but I think it's related to this mixin.

**Comment by nickcolley** [comment] 2019-12-09 11:07
Hey @edwardhorsford,

I've tried to reproduce your issue here:

https://govuk-frontend-issue-1674.glitch.me

```scss
html::before {
  position: absolute;
  background: white;
  padding: 5px;
  font-family: sans-serif;
  @extend %until-mobile-only;
  @extend %mobile-only;
}

%until-mobile-only {
  @include govuk-media-query($until: mobile) {
    content: 'govuk-media-query($until: mobile)';
  }
}

%mobile-only {
  @include govuk-media-query(mobile) {
    content: 'govuk-media-query(mobile)';
  }
}
```

And it seems to output as expected, could you provide some steps to reproduce the issue you're running into please?

**Comment by edwardhorsford** [comment] 2019-12-09 14:57
@nickcolley I wonder if this might be a compiler issue / incompatibility. Your exact snippet above fails for me - we're using `sass-rails`

My snippet also failed for @hannalaakso - so perhaps she can demo.

In the end I've worked around it.

**Comment by kr8n3r** [comment] 2019-12-10 10:52
above snippet will fail to compile in `sass-rails (5.0.6)` but will compile in `sass-rails 6.0.0 ` which is a wrapper for `sassc-rails`

moving  `sassc-rails ` gem comes with it's own set of issues documented here https://github.com/alphagov/govuk-frontend/issues/1350

**Comment by hannalaakso** [comment] 2019-12-11 14:01
I can replicate this in the latest version of the kit (but not in FE review app for instance) with:

```
%display-mobile-only {
  @include govuk-media-query($until: mobile) {
    display: none;
  }
}

.app-sidebar-hr {
  @extend %display-mobile-only;
}
```

**Comment by nickcolley** [comment] 2020-02-21 11:28
OK so this is a bit of a twisty one but I think I've gotten to the bottom of it.

What is happening is that when the Internet Explorer 8 version of the application.css is built. It sets the `$govuk-is-ie8` variable to `true`.

This then sets the `$mq-responsive` variable to `false`.

[`mq` is the library we use to generate our media queries](https://github.com/sass-mq/sass-mq). The responsive variable allows you generate a 'desktop only' build for older browsers, it does this by figuring out which media queries would be shown at 'desktop only' and removing ones on 'mobile'.

This means that when the mixin runs, it outputs nothing, which means your placeholder `%display-mobile-only` class fails to be extended because it's empty.

So you'll see this error message:

```scss
Error: "html::before" failed to @extend "%until-mobile-only".
       The selector "%until-mobile-only" was not found.
       Use "@extend %until-mobile-only !optional" if the extend should be able to fail.
        on line 26 of app/assets/sass/application-ie8.scss
>>     @extend %until-mobile-only;
```

You can work around this by adding `!optional` to your extend, which means when the IE8 file is built it does not break your build.

I think the differences between compilers/wrappers is perhaps how they handle errors in this case.

I have updated my example to include the `$govuk-is-ie8: true` option and now it fails: https://glitch.com/edit/#!/govuk-frontend-issue-1674?path=src/styles/all.scss:2:0

I'm have also raised an issue with sass-mq to see if we can make this better without work arounds: https://github.com/sass-mq/sass-mq/issues/130

## Workaround

- avoid using placeholders with only `govuk-media-query($until)` within them.

or

- use the !optional flag when extending.

I'm going to close this for now as I think this is the best I can offer at this point in time but if there's something I've missed or a better way to work around this feel free to re-open, thanks :)

**Closed by nickcolley** 2020-02-21 11:28 UTC
Labels: Effort: hours, Priority: low, investigation

**Comment by edwardhorsford** [comment] 2020-02-21 11:30
Thanks for investigating this @nickcolley!
