### ISSUE TITLE
Allow Character count hint text to be internationalised

### ISSUE THREAD

**Issue by mgladdish** [alphagov/govuk-frontend#1929] opened 2020-08-26 11:51 UTC
As far as I can see, the "you have x words remaining" hint text under the TextArea on a CharacterCount is done via javscript. Unfortunately this javascript has hard-coded English text.

Ideally we should be able to parameterise all text presented to users, which would also (in our application) allow the text to be presented in any language.

Instead, to support switching languages at runtime, we're going to have to re-do the provided javascript that overwrites the content of the hint. Even the JS implementation itself is really unfriendly to be overridden as it assumes a given sentence structure rather than, say, using a StringFormat-type approach.

I presume that supporting all languages is beyond this project's remit, but surely being able to the provided assets for services in Welsh is a must-have?

**Comment by hannalaakso** [comment] 2020-08-26 12:14
@mgladdish Thanks for flagging this 👍 I'm closing your issue as it's a duplicate of https://github.com/alphagov/govuk-frontend/issues/1681, however if there is anything you wanted to raise that isn't captured on that issue please add a comment to it.

**Closed by hannalaakso** 2020-08-26 12:14 UTC

**Comment by mgladdish** [comment] 2020-08-26 12:26
Thanks. I did search the open issues (honest!) but didn't see that duplicate.

**Comment by hannalaakso** [comment] 2020-08-26 12:51
No problem! 🙂 The issue was opened in https://github.com/alphagov/govuk-design-system so you probably searched there. https://github.com/alphagov/govuk-frontend contains the code for the styles and components that you see on the Design System website so we transferred your issue here.
